config/routes.rb
FoodTruckMap::Application.routes.draw do
  devise_for :users,  controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :users
    resources :food_trucks

    get '/' => 'dashboard#index'
  end

  scope 'api' do
    resources :food_trucks
    resources :tags
  end

  root :to => 'map#index'
end

app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  has_many :schedule_entries
  has_many :locations, through: :schedule_entries

  attr_accessible :name, :description, :twitter_username, :facebook_username, :website_url, :schedule_entries_attributes, :tag_list

  accepts_nested_attributes_for :schedule_entries, reject_if: :all_blank, allow_destroy: true

  default_scope order(:name)

  acts_as_taggable

  def type
    # TODO: update this for seattle
    self.business_type.blank? ? 'stand' : self.business_type
  end

  def status
    # TODO: fix this
    'open'
  end

  def schedule
    # TODO: allow for more than one schedule item per day
    days = {}
    %w[sunday monday tuesday wednesday thursday friday saturday].each do |day|
      # TODO: convert to find_by with rails4
      days[day] = self.schedule_entries.where('day = ?', day).first
    end
    days
  end

  def schedule_for_day(day)
    self.schedule_entries.where('day = ?', day).first
  end

  def self.active_trucks
    ScheduleEntry.where(day: Time.now.strftime("%A").downcase).where('start_time <= ? and end_time >= ?', Time.now, Time.now).map { |s| s.food_truck }
  end
end

app/models/schedule_entry.rb
class ScheduleEntry < ActiveRecord::Base
  belongs_to :food_truck

  attr_accessible :day, :food_truck_id, :end_time, :start_time, :address, :latitude, :longitude

  def self.order_by_case
    ret = "CASE"
    %w[sunday monday tuesday wednesday thursday friday saturday].each_with_index do |day, index|
      ret << " WHEN day = '#{day}' THEN #{index}"
    end
    ret << " END"
  end

  default_scope order(self.order_by_case)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
  end
end

app/controllers/admin/food_trucks_controller.rb
class Admin::FoodTrucksController < AdminController
  # GET /food_trucks
  # GET /food_trucks.json
  def index
    @food_trucks = FoodTruck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_trucks }
    end
  end

  # GET /food_trucks/new
  # GET /food_trucks/new.json
  def new
    @food_truck = FoodTruck.new
    @all_tags = FoodTruck.tag_counts.collect(&:name)

    respond_to do |format|
      format.html
      format.json { render json: @food_truck }
    end
  end

  # GET /food_trucks/1/edit
  def edit
    @food_truck = FoodTruck.find(params[:id])
    @all_tags = FoodTruck.tag_counts.collect(&:name)
  end

  # POST /food_trucks
  # POST /food_trucks.json
  def create
    @food_truck = FoodTruck.new(params[:food_truck])

    respond_to do |format|
      if @food_truck.save
        format.html { redirect_to admin_food_trucks_path, notice: 'Food truck was successfully created.' }
        format.json { render json: @food_truck, status: :created, location: @food_truck }
      else
        format.html { render action: "new" }
        format.json { render json: @food_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_trucks/1
  # PUT /food_trucks/1.json
  def update
    @food_truck = FoodTruck.find(params[:id])

    respond_to do |format|
      if @food_truck.update_attributes(params[:food_truck])
        format.html { redirect_to admin_food_trucks_path(), notice: "Food truck #{@food_truck.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_trucks/1
  # DELETE /food_trucks/1.json
  def destroy
    @food_truck = FoodTruck.find(params[:id])
    @food_truck.destroy

    respond_to do |format|
      format.html { redirect_to admin_food_trucks_url, notice: "Food truck was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ::Devise::SessionsController
  layout 'admin'
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render action: 'new', error: 'There was a problem saving the user.'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].empty? and params[:user][:password_confirmation].empty?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user])
      sign_in(@user, :bypass => true) if @user == current_user
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      redirect_to edit_admin_user_path(@user), alert: 'There was a problem saving the user.'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully deleted.'
    else
      redirect_to edit_admin_user_path(@user), alert: 'There was a problem deleting the user.'
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_out_path_for(resource_or_scope)
    admin_path
  end
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  def index
    @food_trucks = FoodTruck.all
    render json: @food_trucks, each_serializer: FoodTruckSerializer, root: false
  end

  def show
    @food_truck = FoodTruck.find(params[:id])
    render json: @food_truck
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    @time_durations = (1..6).to_a.map do |x|
      ["Next #{pluralize(x, 'hour')}", "hours_#{x}"]
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = FoodTruck.tag_counts_on(:tags)
    render json: @tags, root: false
  end
end

app/helpers/admin/bootstrap_flash_helper.rb
module Admin::BootstrapFlashHelper
  ALERT_TYPES = [:danger, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = :success if type == :notice
      type = :danger   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nilsafe_time_ago_in_words(datetime)
    if datetime.nil?
      'Never'
    else
      "#{time_ago_in_words(datetime).capitalize} ago"
    end
  end

  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/food_trucks_helper.rb
module FoodTrucksHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/admin/dashboard/index.haml
%p This is admin dashboard

app/views/admin/food_trucks/_form.haml
= simple_form_for [:admin, @food_truck], html: { class: 'form-horizontal' } do |f|
  - if @food_truck.errors.any?
    #error_explanation
      %h2
        = pluralize(@food_truck.errors.count, "error")
        prohibited this food_truck from being saved:
      %ul
        - @food_truck.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :name, class: 'form-control'

  .form-group
    = f.label :tags, class: 'col-sm-2 control-label', for: :food_truck_tag_list
    .col-sm-10
      = f.input_field :tag_list, style: 'width: 100%'
      :coffee
        window.all_tags = #{@all_tags.to_json}


  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :description, class: 'form-control', rows: 5

  .form-group
    = f.label :twitter_username, 'Twitter URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :twitter_username, class: 'form-control'

  .form-group
    = f.label :facebook_username, 'Facebook URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :facebook_username, class: 'form-control'

  .form-group
    = f.label :website_url, 'Website URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :website_url, class: 'form-control'

  .row
    .col-sm-offset-2.col-sm-10
      %h4 Schedule
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th
            %th Start Time
            %th End Time
            %th Display Address
            %th Lat/Lng
            %th
        %tbody#schedule_entries
          = f.simple_fields_for :schedule_entries do |schedule_entry|
            = render 'schedule_entry_fields', f: schedule_entry
      %p= link_to_add_association 'add schedule entry', f, :schedule_entries, :'data-association-insertion-node' => 'tbody#schedule_entries', :'data-association-insertion-method' => 'append'

  .form-group.actions
    .col-sm-offset-2.col-sm-10
      = f.button :submit, 'Submit'
      - if params[:action] == 'edit'
        %p.delete-link
          = link_to 'Delete Food Truck', admin_food_truck_path, method: :delete, data: { confirm: 'Are you sure you want to delete this food truck?' }

app/views/admin/food_trucks/_schedule_entry_fields.haml
%tr.nested-fields
  %td= f.input_field :day, collection: %w[sunday monday tuesday wednesday thursday friday saturday]
  %td= f.input_field :start_time
  %td= f.input_field :end_time
  %td= f.input_field :address, style: 'width: 200px'
  %td
    = f.label :latitude, 'Lat'
    = f.input_field :latitude, style: 'width: 80px'
    %br
    = f.label :longitude, 'Lng'
    = f.input_field :longitude, style: 'width: 80px'
  %td= link_to_remove_association 'delete', f

app/views/admin/food_trucks/edit.haml
%h1
  %span.text-muted Editing Food Truck:
  %span= @food_truck.name

= render 'form'

app/views/admin/food_trucks/index.haml
%h1 Food Trucks

%p
  = link_to new_admin_food_truck_path do
    %span.glyphicon.glyphicon-plus
    New Food Truck

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th # Schedule Entries
      %th Last Update
  %tbody
    - @food_trucks.each do |food_truck|
      %tr
        %td
          = link_to food_truck.name, edit_admin_food_truck_path(food_truck)
        %td
          = food_truck.schedule_entries.count
        %td
          = food_truck.updated_at.strftime('%b %d %Y, %H:%M')

app/views/admin/food_trucks/new.haml
%h1 New Food Truck

= render 'form'

= link_to 'Back', admin_food_trucks_path

app/views/admin/food_trucks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_food_truck_path(@admin_food_truck) %> |
<%= link_to 'Back', admin_food_trucks_path %>

app/views/admin/users/_form.haml
= simple_form_for [:admin, @user], html: { class: 'form-horizontal' } do |f|
  - if @user.errors.any?
    #error_explanation
      %h3
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul.validation_errors
        - @user.errors.full_messages.each do |msg|
          %li= msg

  - if params[:action] == 'edit'
    .form-group
      .col-sm-10.col-sm-offset-2
        = image_tag avatar_url(@user, 150)

  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :email, class: 'form-control'

  - if params[:action] == 'edit'
    .form-group
      = f.label :last_sign_in_at, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.last_sign_in_at

    .form-group
      = f.label :last_sign_in_ip, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.last_sign_in_ip

    .form-group
      = f.label :created_at, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.created_at

  .form-group
    - if params[:action] == 'edit'
      .col-sm-10.col-sm-offset-2
        %p
          %em Leave password blank to keep it unchanged.

  .form-group
    = f.label :password, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :password_confirmation, class: 'form-control'

  .form-group.actions
    .col-sm-offset-2.col-sm-10
      = f.button :submit, 'Submit'
      - if params[:action] == 'edit'
        %p.delete-link
          = link_to 'Delete User', admin_user_path, method: :delete, data: { confirm: 'Are you sure you want to delete this user?' }

app/views/admin/users/edit.haml
%h1
  %span.text-muted Editing User
  %span= @user.email

= render 'form'

app/views/admin/users/index.haml
%h1 Users

%p
  = link_to new_admin_user_path do
    %span.glyphicon.glyphicon-plus
    New User

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Email
      %th Last Login
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.email, edit_admin_user_path(user)
        %td= user.last_sign_in_at

app/views/admin/users/new.haml
%h1
  %span.text-muted New User

= render 'form'

app/views/layouts/admin.haml
!!! HTML
%html
  %head
    %title= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
    = stylesheet_link_tag 'admin', media: 'all'
    = csrf_meta_tags
  %body
    %nav(class="navbar navbar-default" role="navigation")
      %div.container
        %div.navbar-header
          %button(type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse")
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a(class="navbar-brand")= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
        - if user_signed_in?
          %div(class="collapse navbar-collapse navbar-ex1-collapse")
            %ul(class="nav navbar-nav")
              %li{class: ('active' if params[:controller] == 'admin/dashboard')}
                = link_to 'Dashboard', admin_path()
              %li{class: ('active' if params[:controller] == 'admin/food_trucks')}
                = link_to 'Food Trucks', admin_food_trucks_path()
              %li{class: ('active' if params[:controller] == 'admin/users')}
                = link_to 'Users', admin_users_path()
            %ul(class="nav navbar-nav navbar-right")
              %li
                %a(href='#') Profile
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
    %div.container
      = bootstrap_flash
      = yield
    = javascript_include_tag 'admin'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body{"ng-app" => "food_truck_app", "ng-controller" => "food_trucks_controller as food_trucks"}
    .container.fill-height
      .row.fill-height
        .fill-height.col-sm-3.navigation
          %h1
            = link_to 'Food Truck Map', root_path
            %span.beta BETA
          = yield
        #map.col-sm-9.fill-height
    = javascript_include_tag 'application'
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-43961581-2', 'seattlefoodtrucks.herokuapp.com');
      ga('send', 'pageview');

app/views/map/checkin.html.erb
<h3 ng-init="enable_checkin()">Check In</h3>
<%= form_for :check_in, url: '/checkin' do |f| %>
  <p>Drag the pin on the map to your current location.</p>
  <p>
    <%= f.label 'address' %>
  <div>{{check_in_address}}</div>
  <%= f.hidden_field :address, value: '{{check_in_address}}' %>
  </p>
  <%= f.label 'Duration' %>
  <%= f.select :duration, options_for_select(@time_durations), include_blank: true %>
  <p><%= f.submit 'Check In' %></p>
<% end %>

app/views/map/index.haml
%p.truck-filter
  %label.control-label(for='filter') Filter
  %select#filter(style='width: 100%' multiple='multiple'){'ng-model' => 'active_tags'}
    %option{'ng-repeat' => 'tag in food_trucks.all_tags'} {{tag.name}}

%h4 Food Trucks
%table.table.table-striped.table-bordered.table-hover
  %tr{"ng-repeat" => "truck in food_trucks.all_trucks | filter_by_tags:active_tags"}
    %td
      %a{href: "#", "ng-click" => "food_trucks.show_truck(truck)"} {{truck.name}}